# Site Settings
title: SnailShell
slogan: Home for PowerSnail
description: My Home Page
author: powersnail
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://powersnail.com"
# improve_content: https://github.com/Phlow/feeling-responsive/edit/gh-pages
logo: "logo.svg"
language: 'en'


# paginate: 5                      # Paginates all X entries
# paginate_path: "blog/page:num"   # Pagination path › Important for blog page in /blog/ to work


# Build Settings
markdown: kramdown
permalink          : /:categories/:title/
highlight          : rouge
excerpt_separator  : "<!--more-->"
include            : ['.htaccess']
plugins:
  - jekyll-feed
  - jekyll-asciidoc
  - jekyll-gist
  - jekyll-paginate

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]

# Exclude these files from your production _site
exclude:
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - INSTALL.md
  - vendor
  - _drafts/


# Theme related

defaults:
  -
    scope:
      path: '' 				# an empty string here means all files in the project
      type: 'pages'
    values:
      show_meta: false 	# Hide metadata for all pages
      comments: false
      author: powersnail     # Default author for pages
  -
    scope:
      path: ''
      type: 'posts'
    values:
      show_meta: true   # Show metadata for all posts
      comments: false
      author: powersnail     # Default author for posts

favicon-32x32:                          'icon32x32.png'
touch-icon-192x192:                     'icon192x192.png'
apple-touch-icon-180x180-precomposed:   'icon180x180.png'
apple-touch-icon-152x152-precomposed:   'icon152x152.png'
apple-touch-icon-144x144-precomposed:   'icon144x144.png'
apple-touch-icon-120x120-precomposed:   'icon120x120.png'
apple-touch-icon-114x114-precomposed:   'icon114x114.png'
apple-touch-icon-76x76-precomposed:     'icon76x76.png'
apple-touch-icon-72x72-precomposed:     'icon72x72.png'
apple-touch-icon-precomposed:           'icon57x57.png'
msapplication_tileimage:                'icon144x144.png'
msapplication_tilecolor:                '#fabb00'

sass:
    sass_dir : _sass
    style    : :compressed

asciidoctor-enabled: false
asciidoctor:
  description: testtewtetrue
  attributes:
    source-highlighter: coderay
    coderay-css: style
    icons: font
