baseURL = "https://powersnail.com/"
languageCode = "en-us"
title = "SnailShell"
hasCJKLanguage = true
ignorefiles = ["output"]
summaryLength = 20

[markup]
[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false
[markup.goldmark.parser.attribute]
block = true
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
anchorLineNos = false
codeFences = true
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNumbersInTable = true
noClasses = true
style = 'pygments'
tabWidth = 4

[author]
name = "PowerSnail"

[params]
about = "I'm PowerSnail. A coder, music lover, and an enthusiastic cook."
favicon = "/images/snail.svg"
lang = "en"
theme_color = "#bd1b37"
responsiveImageSizes = [400, 600, 800, 1000, 1200]
# christmas = true

[permalinks]
posts = "/:year/:slug/"
