baseURL = "https://powersnail.com/"
languageCode = "en-us"
title = "SnailShell"
hasCJKLanguage = true
paginate = 20
ignorefiles = ["output"] 
summaryLength = 12
disableKinds = ["section"]

[markup]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
anchorLineNos = false
codeFences = true
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNumbersInTable = true
noClasses = false
style = 'pygments'
tabWidth = 4

[author]
name = "PowerSnail"

[outputs]
  posts     = ["HTML", "RSS"]
  section  = ["HTML"]

[params]
about = "I'm PowerSnail. A coder, music lover, and an enthusiastic cook."
favicon = "/images/snail.svg"
lang = "en"

[permalinks]
posts= "/:year/:slug/"
