baseURL = "https://powersnail.com/"
languageCode = "en-us"
title = "SnailShell"
theme = "rocinante"
hasCJKLanguage = true

[markup]
  [markup.goldmark.renderer]
    unsafe= true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNumbersInTable = true
    noClasses = true
    style = 'dracula'
    tabWidth = 4

[author]
  name = "PowerSnail"

[params]
  about = "I'm PowerSnail. A coder, music lover, and an enthusiastic cook."
  favicon = "/images/snail.svg"
  lang = "en"

  