baseURL = "/"
languageCode = "en-us"
title = "SnailShell"
theme = "rocinante"
hasCJKLanguage = true

[markup]
  [markup.goldmark.renderer]
    unsafe= true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNumbersInTable = true
    noClasses = true
    style = 'dracula'
    tabWidth = 4

[author]
  name = "PowerSnail"

[params]
  mainSections = ["comsci", "reading", "recipes", "studies"]
  about = "I'm PowerSnail. A coder, music lover, and an enthusiastic cook."
  favicon = "/images/snail.svg"

  [[params.links]]
    [[params.links.link]]
      name = "Computer Science"
      href = "/comsci"
    [[params.links.link]]
      name = "Reading"
      href = "/reading"
    [[params.links.link]]
      name = "Recipes"
      href = "/recipes"
    [[params.links.link]]
      name = "Studies"
      href = "/studies"
    [[params.links.link]]
      name = "About"
      href = "/about"
