baseURL = "/"
languageCode = "en-us"
title = "SnailShell"
theme = "rocinante"
hasCJKLanguage = true

[markup]
  [markup.highlight]
    style = "monokailight"
    tabWidth = 2
  [markup.goldmark.renderer]
    unsafe= true

[author]
  name = "PowerSnail"

[params]
  mainSections = ["comsci", "reading", "recipes", "studies"]
  about = "I'm PowerSnail. A coder, music lover, and an enthusiastic cook."

  [[params.links]]
    [[params.links.link]]
      name = "Computer Science"
      href = "/comsci"
    [[params.links.link]]
      name = "Reading"
      href = "/reading"
    [[params.links.link]]
      name = "Recipes"
      href = "/recipes"
    [[params.links.link]]
      name = "Studies"
      href = "/studies"
    [[params.links.link]]
      name = "About"
      href = "/about"
