name: Publish Site
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Hugo
        run: |
          sudo apt-get update
          sudo apt-get install -y hugo just fd-find wget curl pandoc
          sudo ln -s $(which fdfind) /usr/bin/fd

      - name: Install LightningCSS & prettier
        run: |
          npm install -g lightningcss
          npm install -g prettier
          sudo ln -s "$(npm get prefix)/bin/prettier" /usr/bin/prettier
          sudo ln -s "$(npm get prefix)/bin/lightningcss" /usr/bin/lightningcss

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install python dependencies
        run: |
          uv sync

      - name: Publish Site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          uv run just publish
